---
title: "Research"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}
</style>

# **My Projects**

## Doctoral Research

Coming soon!<br><br><br><br>

## M.S. Research

During my M.S., I investigated the effects of hydrology (precipitation, drought, flow dynamics) on harmful algae in reservoirs under the supervision of Dr. Adam M. Milewski. My thesis research took place in Lakes Sidney Lanier and Allatoona, two Georgia, U.S.A. reservoirs in the Southeastern Piedmont ecoregion.
<br><br>
### Resulting Publications and Abstracts:

**Knapp, A.S.** and Milewski, A.M., 2020. Spatiotemporal relationships of phytoplankton blooms, drought, and rainstorms in freshwater reservoirs. Water, 12(2), p.404. [DOI: https://doi.org/10.3390/w12020404.](https://doi.org/10.3390/w12020404)

**Knapp, A.S.**, Milewski, A.M., Rotz, R.R., Yilmaz, K.K., Fulton, S., James d.L., Webster, C., 2017. The Role of Drought and Storms in Harmful Algal Bloom Events in Two Georgia Piedmont Reservoirs. Geological Society of America, Abstracts with Program v 49. [Link to abstract.](10.1130/abs/2017AM-304040)

**Knapp, A.S.** and Milewski, A.M., and Rotz, R.R., 2017. Temporal Relationship between Drought-Precipitation Patterns and Freshwater Harmful Algal Blooms in Lake Allatoona, Georgia. Georgia Water Resources Conference, Abstracts with Program. [Link to download program.](http://georgiawaterconference.org/wp-content/uploads/2017/04/2017_GWRC_Program_wCover.pdf)

**Knapp, A.S.**, Milewski, A.M., and Rotz, R.R., 2017. Temporal Relationship between Drought-Precipitation Patterns and the Onset, Duration, and Severity of Freshwater Harmful Algal Blooms in Lake Allatoona, Georgia. Geological Society of America Southeastern Section, Abstracts with Program v 49. [Link to abstract.](10.1130/abs/2017SE-291383)

### Other Publications and Abstracts:

Moorman, M., Hutcheson, H., **Knapp, A.S.**, Creviston, M., Rasmussen, T., and Milewski, A.M., 2019. A Status Assessment of Water Quality on US Fish and Wildlife Refuges in the Southeastern US. 11th National Monitoring Conference, Abstracts with Program. [Link to download presentation.](https://acwi.gov/monitoring/conference/2019/presentations/Moorman_G7_Secure.pdf)

Milewski, A., Rotz, R.R., Al-Dousari, A., Richards, D., **Knapp, A.**, Thomas, M.B., Hutcheson, H. and Durham, M.C., 2018, December. Evaluation of GPM IMERG and TRMM TMPA Precipitation Estimates in the Continental United States and Kuwait. In AGU Fall Meeting Abstracts (Vol. 2018, pp. H43F-2475). [Link to abstract.](https://ui.adsabs.harvard.edu/abs/2018AGUFM.H43F2475M/abstract) <br><br>
<br><br><br><br>
## Undergraduate Research

During my undergraduate work, I worked under Dr. Sam Swanson to investigate primary phosphate mineralogy in a lithium pegmatite, and under Dr. Mike Roden to investigate the petrogenesis of the Banco Bonito rhyolites from the Valles Caldera, NM.
<br><br>
### Resulting Posters and Abstracts:

**Saenger, A.** and Roden, M., 2013. Melt Inclusion Study of the East Fork Rhyolite Member of the Valles Caldera, New Mexico. University of Georgia CURO Symposium, Program & Abstracts. [Link to download proceedings.](https://curo.uga.edu/symposium/BOAs/CURO_BOA_2013.pdf)

**Saenger, A.L.** and Swanson, S.E., 2012. Mineralogy of Primary Phosphate Minerals in Li Pegmatites of the Kings Mountain District, North Carolina. Geological Society of America Southeastern Section, Abstracts with Program v 44. [Link to abstract.](https://gsa.confex.com/gsa/2012SE/webprogram/Paper201989.html)

Hogan, D.L., Tabor, B.M.., Harper, J.R., North, B.K., Vanhazebroek, E., Lawler, J.D., **Saenger, A.L.**, Taylor, N.J., Fleisher, C.J. and Swanson, S.E., 2012. Comparison of Mineralogy of Li Pegmatites in the Kings Mountain District, North Carolina. Geological Society of America Southeastern Section, Abstracts with Program v 44. [Link to abstract.](https://gsa.confex.com/gsa/2012SE/webprogram/Paper201992.html)
<br><br><br><br>
### Other Publications and Abstracts:

Gore, Pamela J. W., Pollack, G.D., and **Saenger, A.L.**, 2009, Two-Year College Collaboration with K-12 Schools and Universities. Geological Society of America, Abstracts with Program v 41. [Link to abstract.](https://gsa.confex.com/gsa/2009AM/webprogram/Paper163246.html)
